### ISSUE TITLE
rust-mdo

### ISSUE THREAD

**Issue by TeXitoi** [goandylok/comp-rs#2]
Hi!

You may be interrested by TeXitoi/rust-mdo (I know, self promotion...)

**Comment by andylokandy** [comment]
Yes!! Its your mdo inspired this crate! But the way mdo work is too hackey, you know, importing some functions to do duck typing. That makes it difficult for multiple monad type to work together. The syntax of comp comes from Scala and Haskell, and some from hado crate, using <- instead of ==<. I know why mdo choose ==<, it is because :pat macro constraining <- , so they're also hacks in comp.
